name: platform_default_sign_in_for_perception
description: A new Flutter package project.
publish_to: none
version: 0.0.0-a1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.3
  google_sign_in: ^6.1.4

  locator_for_perception:
    git: https://github.com/enspyrco/locator_for_perception
  percepts:
    git: https://github.com/enspyrco/percepts
  abstractions:
    git: https://github.com/enspyrco/abstractions
  error_correction_in_perception:
    git: https://github.com/enspyrco/error_correction_in_perception
  
  types_for_auth:
    git: https://github.com/enspyrco/types_for_auth
  json_utils:
    git: https://github.com/enspyrco/json_utils

dev_dependencies:
  flutter_test:
    sdk: flutter
  enspyr_lints:
    git: https://github.com/enspyrco/enspyr_lints

flutter:
