name: platform_default_sign_in_for_perception
description: A new Flutter package project.
version: 0.0.0-a1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.3
  google_sign_in: ^6.1.4

  core_of_perception: ^0.0.0-a1
  locator_for_perception: ^0.0.0-a1
  types_for_perception: ^0.0.0-a1

dev_dependencies:
  flutter_test:
    sdk: flutter
  enspyr_lints: ^0.0.0-a1

flutter:
